authnapp/urls.py
from django.urls import path

import authnapp.views as authnapp

app_name = 'authnapp'

urlpatterns = [

    path('login/', authnapp.login, name='login'),
    path('logout/', authnapp.logout, name='logout'),
    path('register/', authnapp.register, name='register'),
    path('edit/', authnapp.edit, name='edit'),
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path
from mainapp.views import index, products, contact, main
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    #path('products/', products, name='products'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('main/', main, name='main'),
    path('contact/', contact, name='contact'),
    path('auth/', include('authnapp.urls', namespace='auth')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
import mainapp.views as mainapp

app_name = "mainapp"

urlpatterns = [
    path('', mainapp.products, name='index'),
    path('<int:pk>/', mainapp.products, name='categoryes'),
]

authnapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.


class ShopUser(AbstractUser):
    avatar = models.ImageField(blank=True)
    age = models.PositiveIntegerField(verbose_name='возраст')

mainapp/models.py
from django.db import models


# Create your models here.


class ProductCategory(models.Model):
    name = models.CharField(verbose_name="имя", max_length=64, unique=True)
    descriptions = models.TextField(verbose_name="описание", blank=True)

    def __str__(self):
        return self.name


class Products(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name="краткое описание товара", max_length=60, blank=True)
    description = models.TextField(verbose_name="описание продукта", blank=True)
    price = models.DecimalField(verbose_name="цена продукта", max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name="количество на складе", default=0)

    def __str__(self):
        return f"{self.name} ({self.category.name})"

authnapp/views.py
from django.http import HttpResponse
from django.shortcuts import render,HttpResponseRedirect
from django.contrib import auth
from django.urls import  reverse
# Create your views here.
from authnapp.forms import ShopUserLoginForm, ShopUserRegisterForm, ShopUserEditForm


def login(request):
    title = 'Вход'

    login_form = ShopUserLoginForm(data=request.POST)
    if request.metod == "POST" and login_form.is_valid():
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)
        if user and user.is_active:
            auth.login(request,user)
            return HttpResponseRedirect('/')
    content = {'title':title, 'login_form': login_form}
    return  render(request, 'authnapp/login.html', content)

def logout(request):
    auth.logout(request)
    return HttpResponseRedirect

def register(request):
    return HttpResponseRedirect('/')
    title = 'регистрация'

    if request.metod == "POST":
        register_form = ShopUserRegisterForm(request.POST, request.FILES)

        if register_form.is_valid():
            register_form.sava()
            return HttpResponseRedirect(reverse('auth:login'))

    else:
        register_form = ShopUserRegisterForm()

        content = {'title':title, 'register_form':register_form}
        return render(request, 'authnapp/register.html', content)


def edit(request):
    title = 'редактирование'

    if request.method == "POST":
        edit_form = ShopUserEditForm(request.POST, request.FILES, instance=request.user)
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('auth:edit'))
        else:
            edit_form = ShopUserEditForm(instance=request.user)

        content = {'title':title, 'edit_form': edit_form}
        return render(request, 'authnapp/edit.html', content)

mainapp/views.py
from django.shortcuts import render
from django.templatetags.static import static
import os
import json
from mainapp.models import Products, ProductCategory
# Create your views here.

module_dir = os.path.dirname(__file__,)

links_menu = [
        {'href': 'products_all', 'name': 'все'},
        {'href': 'products_home', 'name': 'дом'},
        {'href': 'products_office', 'name': 'офис'},
        {'href': 'products_modern', 'name': 'модерн'},
        {'href': 'products_classic', 'name': 'классика'},
    ]

menu = [
        {'href': 'index', 'name': 'главная'},
        {'href': 'products:index', 'name': 'продукты'},
        {'href': 'contact', 'name': 'контакты'},
]

def index(request):
    context = {'title':'Магазин', 'menu':menu}
    return render(request, "mainapp/index.html", context)

def products(request, pk=None):
    print(pk)
    file_path = os.path.join(module_dir, 'json/products.json')
    products = json.load(open(file_path, encoding='utf-8'))



    title = 'Продукты'
    product = Products.objects.all()[:4]
    content = {'title': title,
        'links_menu': links_menu,
        'products': product,
        'menu': menu,
    }
    # content = {'title': title, 'products': product}


    return render(request, 'mainapp/products.html', content)

def contact(request):
    context = {'title': 'Контакты', 'menu':menu}
    return render(request, "mainapp/contact.html", context)

def main(request):
     title = 'главная'
     product = Products.objects.all()[:4]
     content = {'title': title,
                'links_menu': links_menu,
                'products': product,
                'menu': menu,
                }
     return render(request, 'mainapp/products.html', content)

authnapp/templates/authnapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<meta charset="utf-8">
	<title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
	    <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
    {% block js %}

    {% endblock %}
</head>
<body>
	<div class="container">
        <div class="login">
            <div class="h2 text-center head">
                Вход в систему
            </div>

            {% block content %}

            {% endblock %}
        </div>
	</div>
</body>
</html>

authnapp/templates/authnapp/edit.html
{% extends 'authnapp/base.html' %}
{% load static %}


{% block content %}
    <div class="user_avatar"><img src="/media/{{ user.avatar }}"></div>
    <form class="form-horizontal" action="{% url 'auth:edit' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ edit_form.as_p }}
            <input class="btn btn-primary" type="submit" value="Сохранить">

    </form>
{% endblock %}

authnapp/templates/authnapp/login.html
{% extends 'authnapp/base.html' %}
{% load static %}


{% block content %}
    <form class="form-horizontal" action="{% url 'auth:login' %}" method="post">
            {% csrf_token %}
            {{ login_form.as_p }}
            <br>
            <input class="form-control" type="submit" value="Войти">
    </form>
    </hr>
    <a href="{% url 'auth:register' %}">Регистрация</a>>
{% endblock %}

authnapp/templates/authnapp/register.html
{% extends 'authnapp/base.html' %}
{% load static %}


{% block content %}
    <form class="form-horizontal" action="{% url 'auth:register' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ register_form.as_p }}
            <input class="btn btn-primary" type="submit" value="Зарегистрироваться">

    </form>
            <hr>
            <a href="{% url 'auth:login' %}">Войти</a>>

{% endblock %}

mainapp/templates/mainapp/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
    <title>
    {% block title %}
     {{ title|title }}
    {% endblock %}
    </title>
    {% block css %}
	<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
	<link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
    {% block js %}
    {% endblock %}
</head>
<body>
	<div class="container">
        {% block menu %}
        {% endblock %}
        {% block content %}
        {% endblock %}
		</div>

		<div class="clr"></div>

	</div>
    {% block footer %}
    <div class="footer">
        <div class="clearfix">
            <div class="text-footer">
                <h3>контакты</h3>
            </div>
            <div class="text-footer">
                <h3>полезная информация</h3>
            </div>
            <div class="text-footer clearfix">
                <h3>Оставайтесь на связи</h3>
                <p>Подписаться на новости и рассылки</p>
                <form>
                    <input type="email" name="email" placeholder="ваш email">
                    <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
                </form>
            </div>
        </div>
        <p class="small">&copy; GB {% now "Y" %}</p>
        <div class="social">
            <a href="#" class="social1"></a>
            <a href="#" class="social2"></a>
            <a href="#" class="social3"></a>
            <a href="#" class="social4"></a>
        </div>
        <p class="small">Положения &amp; Условия  /  Конфиденциальность &amp; Cookies</p>
    </div>
    {% endblock %}
</body>
</html>

mainapp/templates/mainapp/contact.html
{% extends 'mainapp/base.html' %}
{% block title %}
	{{ title|title }}
{% endblock %}
		{% block menu %}
		<div class="hero">
			<div class="header clearfix">
				<a href="{% url 'index' %}" class="logo"></a>
				{% include 'mainapp/includes/inc__main_menu.html' %}
				<a href="#" class="search"></a>
                <a href="#" class="basket"></a>
			</div>
			<h1>наши контакты</h1>
		</div>
		{% endblock %}
		{% block content %}
		<div class="location">
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
		</div>
		{% endblock %}
		<div class="clr"></div>
	</div>
</body>
</html>

mainapp/templates/mainapp/includes/inc__main_menu.html
<ul class="menu">
    {% for link in menu %}
    <li>
        <a href="{% url link.href %}"
            class ="{% if request.resolver_match.url_name == link.href %}
            active
            {% endif %}">
            {{ link.name }}
        </a>

    </li>
    {% endfor %}

            {% if user.is_authenticated %}
            <li><a href="{% url 'auth:edit' %}">{{ user.first_name|default:"Пользователь" }}</a></li>
            <li><a href="{% url 'auth:logout' %}">Выйти</a></li>
        {% else %}
            <li><a href="{% url 'auth:register' %}">Регистрация</a></li>
            <li><a href="{% url 'auth:login' %}">Войти</a></li>
        {% endif%}
</ul>

mainapp/templates/mainapp/includes/inc_categories_menu.html
<ul class="links-menu">
    {% for link in links_menu %}
    <li>
        <a href="#"
            class="{% if request.resolver_match.url_name == '' %}
            active
            {% endif %}">
            {{ link.name }}
        </a>
    </li>
    {% endfor %}
</ul>

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% block title %}
	{{ title|title }}
{% endblock %}
		{% block menu %}
		<div class="slider">
			<div class="header clearfix">
				<a href="{% url 'index' %}" class="logo"></a>
				{% include 'mainapp/includes/inc__main_menu.html' %}
				<a href="#" class="search"></a>
			</div>
			<div class="text-slider">
				<h3 class="green">тенденции {% now "Y" %}</h3>
				<h3 class="big"> удобные стулья</h3>
				<p>Новый уровень комфорта. Отличные характеристики.</p>
				<a href="#" class="button-order">заказать <img src="/static/img/arrow.png" alt=""></a>
			</div>
			<div class="navi">
				<a href="#"></a><a href="#"></a><a href="#"></a>
			</div>
		</div>
		{% endblock %}
		{% block content %}
		<div class="featured">
			<div class="featured-menu">
					<a class="active" href="#">Популярные</a><a href="#">Новинки</a>
			</div>
			<a class="explore" href="#">показать все <img src="/static/img/arrow.png" alt=""></a>
			<div class="clearfix">
			</div>
			<div class="tab-content">
				<div class="block">
					<a href="#"><img src="/static/img/product-1.jpg" alt="">
						<div class="text">
							<img src="/static/img/icon-hover.png" alt="img">
							<h4>Отличный стул</h4>
							<p>Расположитесь комфортно. </p>
						</div>
					</a>
				</div>
				<div class="block">
					<a href="#"><img src="/static/img/product-2.jpg" alt="">
						<div class="text">
							<img src="/static/img/icon-hover.png" alt="">
							<h4>Стул повышенного качества</h4>
							<p>Не оторваться. </p>
						</div>
					</a>
				</div>
			</div>
		</div>
		{% endblock %}
		<div class="clr"></div>
	</div>
</body>
</html>

mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% block title %}
	{{ title|title }}
{% endblock %}
		{% block menu %}
		<div class="hero-white">
			<div class="header clearfix">
				<a href="{% url 'index' %}" class="logo"></a>
				{% include 'mainapp/includes/inc__main_menu.html' %}
				<a href="#" class="search"></a>
                <a href="#" class="basket"></a>
			</div>
		</div>
		{% endblock %}
		{% block content %}
		<div class="details">
			<div class="links clearfix">
				{% include 'mainapp/includes/inc_categories_menu.html' %}
			</div>
			<div class="details-products">
				<div class="details-slider">
					<div class="slider-product">
						<img src="/static/img/slider1.jpg">
					</div>
					<div class="slider-control">
						<div class="block">
							<a href="#"><img src="/static/img/controll.jpg" alt="">
								<div class="text"></div>
							</a>
						</div>
						<div class="block">
							<a href="#"><img src="/static/img/controll1.jpg" alt="">
								<div class="text"></div>
							</a>
						</div>
						<div class="block">
							<a href="#"><img src="/static/img/controll2.jpg" alt="">
								<div class="text"></div>
							</a>
						</div>
					</div>
				</div>

				<div class="description">
					<h3 class="big-bold">Отличный стул</h3>
					<h3 class="red">горячее предложение</h3>
					<p class="price"> 2585.9 <span>руб</span></p>
					<a href="#" class="red-button">
						заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
					</a>
					<div class="description-text">
						<p>Расположитесь комфортно.</p>
						<p>Отличное качество материалов
						позволит вам это.</p>
						<p>Различные цвета</p>
						<p>высочайший уровень
						эргономики и прочность.</p>
					</div>
				</div>
			</div>

			<div class="related">
				<div class="title clearfix">
					<h2>Похожие продукты</h2>
					<a class="explore" href="#">показать все <img src="/static/img/arrow.png" alt=""></a>
				</div>
				<div class="related-products clearfix">
					{% for product in products %}
					<div class="block">
						<a href="#"><img src="/media/{{ product.image }}" alt="">
							<div class="text">
								<img src="/static/img/icon-hover.png" alt="img">
								<h3>{{ product.category.name }}</h3>
								<h4>{{ product.name }}</h4>
								<p>{{ product.descriptions }}</p>
							</div>
						</a>
					</div>
					{% endfor %}

				</div>
			</div>
		</div>
		{% endblock %}
		<div class="clr"></div>
	</div>
</body>
</html>

mainapp/templates/mainapp/test_context.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{title}}</title>
</head>
<body>
<h1>{{header}}</h1>
<p>{{username}}</p>
{% for product in products %}
    <h3>{{product.name}}</h3>
    <p>{{product.price}}</p>
{% endfor %}
</body>
</html>